
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package gnz.analizadores;

/** CUP generated class containing symbol constants. */
public class CommunicationSym {
  /* terminals */
  public static final int PARENTHESISO = 3;
  public static final int MOVESTRAIGHT = 9;
  public static final int BEHIND = 13;
  public static final int UP = 14;
  public static final int PARENTHESISC = 4;
  public static final int MOVEDIAGONAL = 10;
  public static final int COMMA = 2;
  public static final int EOF = 0;
  public static final int AHEAD = 12;
  public static final int error = 1;
  public static final int DEGREES = 17;
  public static final int DOWN = 15;
  public static final int MOVECURVED = 11;
  public static final int INTEGER = 18;
  public static final int SEG = 16;
  public static final int MOVED = 8;
  public static final int MOVEC = 7;
  public static final int MOVEB = 6;
  public static final int MOVEA = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMMA",
  "PARENTHESISO",
  "PARENTHESISC",
  "MOVEA",
  "MOVEB",
  "MOVEC",
  "MOVED",
  "MOVESTRAIGHT",
  "MOVEDIAGONAL",
  "MOVECURVED",
  "AHEAD",
  "BEHIND",
  "UP",
  "DOWN",
  "SEG",
  "DEGREES",
  "INTEGER"
  };
}

