
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package gnz.analizadores;

import java_cup.runtime.*;
import java.util.LinkedList;
import gnz.backend.objetoMovil.Movimiento;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser1 extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym1.class;
}

  /** Default constructor. */
  @Deprecated
  public parser1() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser1(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser1(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\016\000\002\002\004\000\002\002\007\000\002\005" +
    "\004\000\002\005\003\000\002\004\013\000\002\004\014" +
    "\000\002\004\015\000\002\004\015\000\002\004\015\000" +
    "\002\004\015\000\002\003\003\000\002\003\003\000\002" +
    "\003\003\000\002\003\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\064\000\004\007\005\001\002\000\004\002\066\001" +
    "\002\000\004\011\006\001\002\000\010\012\007\013\010" +
    "\014\013\001\002\000\004\005\052\001\002\000\004\005" +
    "\041\001\002\000\012\010\ufffe\012\ufffe\013\ufffe\014\ufffe" +
    "\001\002\000\012\010\036\012\007\013\010\014\013\001" +
    "\002\000\004\005\014\001\002\000\004\023\015\001\002" +
    "\000\004\021\016\001\002\000\004\004\017\001\002\000" +
    "\004\023\020\001\002\000\004\004\021\001\002\000\006" +
    "\015\023\016\022\001\002\000\004\004\031\001\002\000" +
    "\004\004\024\001\002\000\006\017\025\020\026\001\002" +
    "\000\004\006\030\001\002\000\004\006\027\001\002\000" +
    "\012\010\ufffa\012\ufffa\013\ufffa\014\ufffa\001\002\000\012" +
    "\010\ufffb\012\ufffb\013\ufffb\014\ufffb\001\002\000\006\017" +
    "\032\020\033\001\002\000\004\006\035\001\002\000\004" +
    "\006\034\001\002\000\012\010\ufff8\012\ufff8\013\ufff8\014" +
    "\ufff8\001\002\000\012\010\ufff9\012\ufff9\013\ufff9\014\ufff9" +
    "\001\002\000\004\011\040\001\002\000\012\010\uffff\012" +
    "\uffff\013\uffff\014\uffff\001\002\000\004\002\000\001\002" +
    "\000\004\023\042\001\002\000\004\021\043\001\002\000" +
    "\004\004\044\001\002\000\004\023\045\001\002\000\004" +
    "\004\046\001\002\000\004\023\047\001\002\000\004\022" +
    "\050\001\002\000\004\006\051\001\002\000\012\010\ufffc" +
    "\012\ufffc\013\ufffc\014\ufffc\001\002\000\004\023\053\001" +
    "\002\000\004\021\054\001\002\000\004\004\055\001\002" +
    "\000\004\023\056\001\002\000\004\004\057\001\002\000" +
    "\012\015\063\016\062\017\061\020\064\001\002\000\004" +
    "\006\065\001\002\000\004\006\ufff5\001\002\000\004\006" +
    "\ufff6\001\002\000\004\006\ufff7\001\002\000\004\006\ufff4" +
    "\001\002\000\012\010\ufffd\012\ufffd\013\ufffd\014\ufffd\001" +
    "\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\064\000\004\002\003\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\004\010\005\011\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\004" +
    "\036\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\003\057\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser1$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser1$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser1$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public LinkedList<Movimiento> listavalores;

    /**
     * Método al que se llama automáticamente ante algún error sintactico.
     **/ 
    public void syntax_error(Symbol s){ 
        int fil = (s.right)+1;
        int col = (s.left)+1;
        System.out.println("Error Sintáctico en la Línea " + (col) +
        " Columna "+(fil)+ ". No se esperaba este componente: " +s.value+"."); 
    } 

    /**
     * Método al que se llama automáticamente ante algún error sintáctico 
     * en el que ya no es posible una recuperación de errores.
     **/ 
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{ 
        int fil = (s.right)+1;
        int col = (s.left)+1;
        System.out.println("Error síntactico irrecuperable en la Línea " + 
        (col)+ " Columna "+(fil)+". Componente " + s.value + 
        " no reconocido."); 
    }  


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser1$actions {
  private final parser1 parser;

  /** Constructor */
  CUP$parser1$actions(parser1 parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser1$do_action_part00000000(
    int                        CUP$parser1$act_num,
    java_cup.runtime.lr_parser CUP$parser1$parser,
    java.util.Stack            CUP$parser1$stack,
    int                        CUP$parser1$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser1$result;

      /* select the action based on the action number */
      switch (CUP$parser1$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= S EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser1$stack.elementAt(CUP$parser1$top-1)).value;
		RESULT = start_val;
              CUP$parser1$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-1)), ((java_cup.runtime.Symbol)CUP$parser1$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser1$parser.done_parsing();
          return CUP$parser1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // S ::= RIni RTra LVALORES RFin RTra 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-2)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-2)).right;
		LinkedList<Movimiento> a = (LinkedList<Movimiento>)((java_cup.runtime.Symbol) CUP$parser1$stack.elementAt(CUP$parser1$top-2)).value;
		
    parser.listavalores=a;
    
              CUP$parser1$result = parser.getSymbolFactory().newSymbol("S",0, ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-4)), ((java_cup.runtime.Symbol)CUP$parser1$stack.peek()), RESULT);
            }
          return CUP$parser1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // LVALORES ::= LVALORES VALOR 
            {
              LinkedList<Movimiento> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-1)).right;
		LinkedList<Movimiento> a = (LinkedList<Movimiento>)((java_cup.runtime.Symbol) CUP$parser1$stack.elementAt(CUP$parser1$top-1)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser1$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser1$stack.peek()).right;
		Movimiento b = (Movimiento)((java_cup.runtime.Symbol) CUP$parser1$stack.peek()).value;
		
    RESULT=a;
    RESULT.add(b);
    
              CUP$parser1$result = parser.getSymbolFactory().newSymbol("LVALORES",3, ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-1)), ((java_cup.runtime.Symbol)CUP$parser1$stack.peek()), RESULT);
            }
          return CUP$parser1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // LVALORES ::= VALOR 
            {
              LinkedList<Movimiento> RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser1$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser1$stack.peek()).right;
		Movimiento a = (Movimiento)((java_cup.runtime.Symbol) CUP$parser1$stack.peek()).value;
		
    LinkedList<Movimiento> listavalores= new LinkedList<Movimiento>();
    RESULT=listavalores;
    RESULT.add(a);
    
              CUP$parser1$result = parser.getSymbolFactory().newSymbol("LVALORES",3, ((java_cup.runtime.Symbol)CUP$parser1$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser1$stack.peek()), RESULT);
            }
          return CUP$parser1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // VALOR ::= RMre Para numerico Rcm com numerico com DIRECCION Parc 
            {
              Movimiento RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-6)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-6)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$parser1$stack.elementAt(CUP$parser1$top-6)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-3)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-3)).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$parser1$stack.elementAt(CUP$parser1$top-3)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-1)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-1)).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$parser1$stack.elementAt(CUP$parser1$top-1)).value;
		
        Movimiento mov=new Movimiento(c, a, b, "0"); 
        RESULT=mov;
    
              CUP$parser1$result = parser.getSymbolFactory().newSymbol("VALOR",2, ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-8)), ((java_cup.runtime.Symbol)CUP$parser1$stack.peek()), RESULT);
            }
          return CUP$parser1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // VALOR ::= RMdi Para numerico Rcm com numerico com numerico RGra Parc 
            {
              Movimiento RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-7)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-7)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$parser1$stack.elementAt(CUP$parser1$top-7)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-4)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-4)).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$parser1$stack.elementAt(CUP$parser1$top-4)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-2)).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-2)).right;
		String c = (String)((java_cup.runtime.Symbol) CUP$parser1$stack.elementAt(CUP$parser1$top-2)).value;
		
        Movimiento mov=new Movimiento("4", a, b, c);
        RESULT=mov;
    
              CUP$parser1$result = parser.getSymbolFactory().newSymbol("VALOR",2, ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-9)), ((java_cup.runtime.Symbol)CUP$parser1$stack.peek()), RESULT);
            }
          return CUP$parser1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // VALOR ::= RMcu Para numerico Rcm com numerico com RAde com RArr Parc 
            {
              Movimiento RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-8)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-8)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$parser1$stack.elementAt(CUP$parser1$top-8)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-5)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-5)).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$parser1$stack.elementAt(CUP$parser1$top-5)).value;
		
        Movimiento mov=new Movimiento("10", a, b);
        RESULT=mov;
    
              CUP$parser1$result = parser.getSymbolFactory().newSymbol("VALOR",2, ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-10)), ((java_cup.runtime.Symbol)CUP$parser1$stack.peek()), RESULT);
            }
          return CUP$parser1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // VALOR ::= RMcu Para numerico Rcm com numerico com RAde com RAba Parc 
            {
              Movimiento RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-8)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-8)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$parser1$stack.elementAt(CUP$parser1$top-8)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-5)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-5)).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$parser1$stack.elementAt(CUP$parser1$top-5)).value;
		
        Movimiento mov=new Movimiento("11", a, b);
        RESULT=mov;
    
              CUP$parser1$result = parser.getSymbolFactory().newSymbol("VALOR",2, ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-10)), ((java_cup.runtime.Symbol)CUP$parser1$stack.peek()), RESULT);
            }
          return CUP$parser1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // VALOR ::= RMcu Para numerico Rcm com numerico com RAtr com RArr Parc 
            {
              Movimiento RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-8)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-8)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$parser1$stack.elementAt(CUP$parser1$top-8)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-5)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-5)).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$parser1$stack.elementAt(CUP$parser1$top-5)).value;
		
        Movimiento mov=new Movimiento("13", a, b);
        RESULT=mov;
    
              CUP$parser1$result = parser.getSymbolFactory().newSymbol("VALOR",2, ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-10)), ((java_cup.runtime.Symbol)CUP$parser1$stack.peek()), RESULT);
            }
          return CUP$parser1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // VALOR ::= RMcu Para numerico Rcm com numerico com RAtr com RAba Parc 
            {
              Movimiento RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-8)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-8)).right;
		String a = (String)((java_cup.runtime.Symbol) CUP$parser1$stack.elementAt(CUP$parser1$top-8)).value;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-5)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-5)).right;
		String b = (String)((java_cup.runtime.Symbol) CUP$parser1$stack.elementAt(CUP$parser1$top-5)).value;
		
        Movimiento mov=new Movimiento("12", a, b);
        RESULT=mov;
    
              CUP$parser1$result = parser.getSymbolFactory().newSymbol("VALOR",2, ((java_cup.runtime.Symbol)CUP$parser1$stack.elementAt(CUP$parser1$top-10)), ((java_cup.runtime.Symbol)CUP$parser1$stack.peek()), RESULT);
            }
          return CUP$parser1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // DIRECCION ::= RAde 
            {
              String RESULT =null;
		
        RESULT="0";
    
              CUP$parser1$result = parser.getSymbolFactory().newSymbol("DIRECCION",1, ((java_cup.runtime.Symbol)CUP$parser1$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser1$stack.peek()), RESULT);
            }
          return CUP$parser1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // DIRECCION ::= RAtr 
            {
              String RESULT =null;
		
        RESULT="1";
    
              CUP$parser1$result = parser.getSymbolFactory().newSymbol("DIRECCION",1, ((java_cup.runtime.Symbol)CUP$parser1$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser1$stack.peek()), RESULT);
            }
          return CUP$parser1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // DIRECCION ::= RArr 
            {
              String RESULT =null;
		
        RESULT="2";    
    
              CUP$parser1$result = parser.getSymbolFactory().newSymbol("DIRECCION",1, ((java_cup.runtime.Symbol)CUP$parser1$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser1$stack.peek()), RESULT);
            }
          return CUP$parser1$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // DIRECCION ::= RAba 
            {
              String RESULT =null;
		
        RESULT="3";
    
              CUP$parser1$result = parser.getSymbolFactory().newSymbol("DIRECCION",1, ((java_cup.runtime.Symbol)CUP$parser1$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser1$stack.peek()), RESULT);
            }
          return CUP$parser1$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser1$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser1$do_action(
    int                        CUP$parser1$act_num,
    java_cup.runtime.lr_parser CUP$parser1$parser,
    java.util.Stack            CUP$parser1$stack,
    int                        CUP$parser1$top)
    throws java.lang.Exception
    {
              return CUP$parser1$do_action_part00000000(
                               CUP$parser1$act_num,
                               CUP$parser1$parser,
                               CUP$parser1$stack,
                               CUP$parser1$top);
    }
}

}
