
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package gnz.analizadores;

/** CUP generated class containing symbol constants. */
public class sym2 {
  /* terminals */
  public static final int MOVERDERECHA = 16;
  public static final int FINTRAYECTO = 9;
  public static final int MOVERARRIBAIZQUIERDA = 19;
  public static final int INI = 6;
  public static final int GIRARDERECHA = 23;
  public static final int PAR_ABIERTO = 11;
  public static final int MOVERABAJODERECHA = 20;
  public static final int MOVERD = 5;
  public static final int MOVERADELANTE = 14;
  public static final int MOVERABAJOIZQUIERDA = 21;
  public static final int MOVERC = 4;
  public static final int MOVERB = 3;
  public static final int COMA = 13;
  public static final int MOVERA = 2;
  public static final int NUMEROS = 10;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int MOVERIZQUIERDA = 17;
  public static final int MOVERATRAS = 15;
  public static final int GIRARIZQUIERDA = 22;
  public static final int PAR_CERRADO = 12;
  public static final int FIN = 7;
  public static final int INITRAYECTO = 8;
  public static final int MOVERARRIBADERECHA = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MOVERA",
  "MOVERB",
  "MOVERC",
  "MOVERD",
  "INI",
  "FIN",
  "INITRAYECTO",
  "FINTRAYECTO",
  "NUMEROS",
  "PAR_ABIERTO",
  "PAR_CERRADO",
  "COMA",
  "MOVERADELANTE",
  "MOVERATRAS",
  "MOVERDERECHA",
  "MOVERIZQUIERDA",
  "MOVERARRIBADERECHA",
  "MOVERARRIBAIZQUIERDA",
  "MOVERABAJODERECHA",
  "MOVERABAJOIZQUIERDA",
  "GIRARIZQUIERDA",
  "GIRARDERECHA"
  };
}

