
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package gnz.analizadores;

/** CUP generated class containing symbol constants. */
public class sym3 {
  /* terminals */
  public static final int RMovA = 9;
  public static final int com = 2;
  public static final int Parc = 4;
  public static final int numerico = 5;
  public static final int Para = 3;
  public static final int EOF = 0;
  public static final int RFin = 7;
  public static final int Ratras = 14;
  public static final int Rcm = 15;
  public static final int RIni = 6;
  public static final int error = 1;
  public static final int Radelante = 13;
  public static final int RMovD = 12;
  public static final int RMovC = 11;
  public static final int RMovB = 10;
  public static final int RTra = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "com",
  "Para",
  "Parc",
  "numerico",
  "RIni",
  "RFin",
  "RTra",
  "RMovA",
  "RMovB",
  "RMovC",
  "RMovD",
  "Radelante",
  "Ratras",
  "Rcm"
  };
}

